/-
Copyright (c) 2026 Larsen Close. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Larsen Close

Tower Morphism Framework (Targets 17/18 merged).

Abstract ω-chain morphism framework + collapse-at-colimit theorem.

Given two ω-chains in a cocomplete category related by a natural transformation
that commutes with the successor operation, the induced morphism at the colimit
is determined by the colimit's universal property. When both chains share a
fixed point (F(L) ≅ L), the transformation collapses.

This is the abstract theorem. Specific instances (CPS vs dimensional chain,
homotopy/homological/topological dimension factoring) are instantiations of the
hypotheses, each ≤20 lines.

## What is proved

- `OmegaChain` : ω-chain in C (functor ℕ ⥤ C)
- `TowerMorphism` : natural transformation between ω-chains
- `towerColimitMap` : induced morphism on colimits
- `towerColimitIso` : nat iso on chains gives iso on colimits
- `GeneratedChain M` : ω-chain generated by iterating endofunctor M
- `GeneratedChainMorphism` : M-compatible morphism between generated chains
- `collapseMap` : the collapse morphism at colimits
- `collapseMap_comm` : commutation with cocone legs
- `collapseMap_unique` : uniqueness from universal property
- `collapseIso` : levelwise iso gives colimit iso
- `sharedCollapseEndo` : endomorphism when chains share a colimit object

STATUS: Tier 1 (0 sorry).
-/

import FixedPoint.Iteration.AdamekTheorem

open CategoryTheory CategoryTheory.Limits

universe v u

namespace FixedPoint.Tower

variable {C : Type u} [Category.{v} C]

/-! ## Part 1: Abstract ω-chain morphisms -/

/-- An ω-chain in C: a functor from (ℕ, ≤) viewed as a category.
    Wraps the Mathlib diagram shape for directed systems. -/
abbrev OmegaChain (C : Type u) [Category.{v} C] := ℕ ⥤ C

/-- A tower morphism between two ω-chains: a natural transformation.
    The naturality condition IS the "commutes with successor" condition —
    for each n, the square

      chain₁(n) --α(n)--> chain₂(n)
         |                    |
      chain₁(n→n+1)      chain₂(n→n+1)
         |                    |
         v                    v
      chain₁(n+1) -α(n+1)-> chain₂(n+1)

    commutes. No additional data needed beyond naturality. -/
abbrev TowerMorphism (F G : OmegaChain C) := F ⟶ G

/-- Two ω-chains are tower-isomorphic if they are related by a natural
    isomorphism. Each level-wise component is an iso, and the squares commute. -/
abbrev TowerIso (F G : OmegaChain C) := F ≅ G

/-! ## Part 2: Induced morphism at colimits -/

section ColimitCollapse

variable (F G : OmegaChain C)
variable [HasColimit F] [HasColimit G]

/-- Given a tower morphism α : F ⟶ G between ω-chains that both have colimits,
    there is an induced morphism colim(F) ⟶ colim(G).
    This is Mathlib's `colimMap`. -/
noncomputable def towerColimitMap (α : TowerMorphism F G) :
    colimit F ⟶ colimit G :=
  colimMap α

/-- A tower isomorphism induces an isomorphism on colimits.
    The abstract "collapse" theorem: if the level-wise correspondence
    is invertible, so is the induced map at the colimit. -/
noncomputable def towerColimitIso (e : TowerIso F G) :
    colimit F ≅ colimit G :=
  HasColimit.isoOfNatIso e

end ColimitCollapse

/-! ## Part 3: Endofunctor-generated chains -/

section EndofunctorChains

variable (M : C ⥤ C)

/-- An endofunctor-generated chain: an ω-chain where each level is produced
    by applying M to the previous level. The Adámek chain
    ⊥ → M(⊥) → M²(⊥) → M³(⊥) → ⋯
    is the canonical example. -/
structure GeneratedChain where
  /-- The underlying ω-chain. -/
  chain : OmegaChain C
  /-- The chain is generated by M: chain(n+1) ≅ M(chain(n)). -/
  generated : ∀ n : ℕ, chain.obj (n + 1) ≅ M.obj (chain.obj n)

/-- A morphism between two M-generated chains: a natural transformation
    between the underlying ω-chains that is compatible with the generating
    isomorphisms. Naturality gives commutation with successor for free;
    this adds commutation with M's action.

      c₁(n+1) ≅ M(c₁(n))
         |           |
       α(n+1)     M(α(n))
         |           |
         v           v
      c₂(n+1) ≅ M(c₂(n))
-/
structure GeneratedChainMorphism (c₁ c₂ : GeneratedChain M) where
  /-- The underlying tower morphism. -/
  morph : TowerMorphism c₁.chain c₂.chain
  /-- The morphism commutes with M's action at each level. -/
  m_compatible : ∀ n : ℕ,
    (c₁.generated n).hom ≫ M.map (morph.app n) =
      morph.app (n + 1) ≫ (c₂.generated n).hom

end EndofunctorChains

/-! ## Part 4: The collapse theorem -/

section Collapse

variable {M : C ⥤ C}
variable (c₁ c₂ : GeneratedChain M)
variable [HasColimitsOfShape ℕ C]

/-- **The Collapse Theorem (map).** Given two M-generated chains with an
    M-compatible morphism, the induced map on colimits is the unique
    morphism determined by the colimit's universal property.

    When the colimits coincide (both are the fixed point L with M(L) ≅ L),
    the induced map is an endomorphism of L. If additionally the morphism
    is an M-compatible natural isomorphism, the induced map is an
    automorphism of L. -/
noncomputable def collapseMap (f : GeneratedChainMorphism M c₁ c₂) :
    colimit c₁.chain ⟶ colimit c₂.chain :=
  colimMap f.morph

/-- The collapse map commutes with the cocone legs:
    ι₁(n) ≫ collapseMap = α(n) ≫ ι₂(n). -/
theorem collapseMap_comm (f : GeneratedChainMorphism M c₁ c₂) (n : ℕ) :
    colimit.ι c₁.chain n ≫ collapseMap c₁ c₂ f =
      f.morph.app n ≫ colimit.ι c₂.chain n :=
  colimit.ι_map f.morph n

/-- The collapse map is unique: any morphism g satisfying the cocone
    leg condition equals collapseMap. -/
theorem collapseMap_unique (f : GeneratedChainMorphism M c₁ c₂)
    (g : colimit c₁.chain ⟶ colimit c₂.chain)
    (hg : ∀ n : ℕ, colimit.ι c₁.chain n ≫ g =
      f.morph.app n ≫ colimit.ι c₂.chain n) :
    g = collapseMap c₁ c₂ f := by
  apply colimit.hom_ext
  intro n
  rw [hg n, ← collapseMap_comm]

/-- When the morphism is a levelwise iso, the collapse is an iso on colimits. -/
noncomputable def collapseIso
    (f : GeneratedChainMorphism M c₁ c₂)
    (hiso : ∀ n : ℕ, IsIso (f.morph.app n)) :
    colimit c₁.chain ≅ colimit c₂.chain :=
  HasColimit.isoOfNatIso
    (NatIso.ofComponents (fun n => asIso (f.morph.app n))
      (fun {_ _} h => f.morph.naturality h))

end Collapse

/-! ## Part 5: Shared fixed point specialization -/

section SharedFixedPoint

variable {M : C ⥤ C}
variable (c₁ c₂ : GeneratedChain M)

/-- When two M-generated chains share the same colimit object L,
    an M-compatible morphism induces an endomorphism of L.

    If additionally M(L) ≅ L (Lambek), this endomorphism respects
    the fixed-point structure. By initiality of the initial algebra,
    when both chains arise from FixedPointSpec, the endomorphism is
    the canonical initial algebra isomorphism. -/
noncomputable def sharedCollapseEndo
    {L : C}
    (κ₁ : Cocone c₁.chain) (hκ₁ : IsColimit κ₁)
    (κ₂ : Cocone c₂.chain) (_ : IsColimit κ₂)
    (e₁ : κ₁.pt ≅ L) (e₂ : L ≅ κ₂.pt)
    (f : GeneratedChainMorphism M c₁ c₂) :
    L ⟶ L :=
  e₁.inv ≫ hκ₁.desc (Cocone.mk κ₂.pt
    { app := fun n => f.morph.app n ≫ κ₂.ι.app n
      naturality := fun {i j} hij => by
        simp only [Functor.const_obj_obj, Functor.const_obj_map, Category.comp_id]
        rw [← Category.assoc, f.morph.naturality, Category.assoc, Cocone.w] }) ≫ e₂.inv

/-- The shared collapse endomorphism commutes with cocone legs
    (up to the identification isos). -/
theorem sharedCollapseEndo_comm
    {L : C}
    (κ₁ : Cocone c₁.chain) (hκ₁ : IsColimit κ₁)
    (κ₂ : Cocone c₂.chain) (hκ₂ : IsColimit κ₂)
    (e₁ : κ₁.pt ≅ L) (e₂ : L ≅ κ₂.pt)
    (f : GeneratedChainMorphism M c₁ c₂) (n : ℕ) :
    κ₁.ι.app n ≫ e₁.hom ≫
      sharedCollapseEndo c₁ c₂ κ₁ hκ₁ κ₂ hκ₂ e₁ e₂ f ≫ e₂.hom =
      f.morph.app n ≫ κ₂.ι.app n := by
  simp only [sharedCollapseEndo, Category.assoc, Iso.hom_inv_id_assoc,
    Iso.inv_hom_id, Category.comp_id]
  exact hκ₁.fac _ n

end SharedFixedPoint

/-! ## Part 6: Connection to project's FixedPointSpec

The project's `FixedPointSpec` provides an Adámek chain with colimit
and Lambek iso. Two `FixedPointSpec`s for the same endofunctor M
produce two `GeneratedChain M`s. A `GeneratedChainMorphism` between
them yields a `sharedCollapseEndo` that is necessarily the identity
(by initiality of the initial algebra — both colimits are initial
algebras, hence isomorphic by a unique iso).

This recovers the paper's claim: the CPS tower and the dimensional
tower, when both formalized as M-generated chains to the same fixed
point, are related by a unique tower morphism whose collapse at
the fixed point is the canonical isomorphism between initial algebras.

Specific instantiations (CPS chain, homotopy dimension chain, etc.)
each require only showing the pair of ω-chains satisfies the
`GeneratedChain` hypotheses — the collapse theorem does the rest. -/

end FixedPoint.Tower
